### ISSUE TITLE
Find better AE pic

### ISSUE THREAD

**Issue by airmencoders** [airmencoders/MQF#14]
Find on DVIDShub or other DoD Public Affairs website.

Submit PR that has a new picture under Assets->AE

**Comment by mabroox130** [comment]
![aeromed](https://user-images.githubusercontent.com/61999447/76272703-1fde8480-624a-11ea-8962-6f7409288bf5.jpg)

I grabbed this from DVIDS. Since there is no face or name associated with it, you should be able to use it without finding the person in the photo. That'll be a problem for any photos with people.

**Comment by airmencoders** [comment]
Do you want to add it and submit a PR? Don't remember if you have xCode or not

**Comment by mabroox130** [comment]
I don’t have Xcode. I can send the file to someone.
